/* This file is autogenerated by tracetool, do not edit. */
/* You must include this file after the inclusion of helper.h */

#ifndef TRACE__GENERATED_TCG_TRACERS_H
#define TRACE__GENERATED_TCG_TRACERS_H

#include <stdint.h>

#include "trace.h"
#include "exec/helper-proto.h"


#endif /* TRACE__GENERATED_TCG_TRACERS_H */
